# Generated by Django 2.2.13 on 2021-01-23 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200910_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='Друзья'),
        ),
    ]
